jwt:
  secret: auhsdfuihpauisdfuhasiudhfuiasuiefjasndjgfbzkxclb/xm;dtjhyiodrtfhjknxdklfgjuiawergfuhasbfdfliughasyurgbhsjzrdgfhiuoshdufgisiarutghstyuerdghjksdfngjseruiygbsjdkfbgnjksdxbfjkgbserbghjdfj
  rtExpiration: 12
  expiration: 3600000

spring:
  datasource: #jdbc:postgresql://postgres.railway.internal:5432/railway
    url: jdbc:postgresql://localhost:5432/TodoTest #jdbc:postgresql://localhost:5432/TodoTest
    username: postgres
    password: 80085 #80085 #EECtbJuEldITiIfBBEIddigCmfvYutJf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
uploads:
  avatars: C:\Users\BoBr\Documents\uploads\avatars #/uploads/avatars/ #C:\Users\BoBr\Documents\uploads\avatars
  images: C:\Users\BoBr\Documents\uploads\images #/uploads/images/ #C:\Users\BoBr\Documents\uploads\images
