jwt:
  secret: auhsdfuihpauisdfuhasiudhfuiasuiefjasndjgfbzkxclb/xm;dtjhyiodrtfhjknxdklfgjuiawergfuhasbfdfliughasyurgbhsjzrdgfhiuoshdufgisiarutghstyuerdghjksdfngjseruiygbsjdkfbgnjksdxbfjkgbserbghjdfj
  rtExpiration: 12
  expiration: 3600000

spring:
  datasource: #jdbc:postgresql://postgres.railway.internal:5432/railway
    url: jdbc:postgresql://postgres.railway.internal:5432/railway #jdbc:postgresql://localhost:5432/TodoTest
    username: postgres
    password: qpmftBIzPAGEKJEcBbiPEKJkShblGNRq #80085 #qpmftBIzPAGEKJEcBbiPEKJkShblGNRq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
uploads:
  avatars: /uploads/avatars/ #/uploads/avatars/ #C:\Users\BoBr\Documents\uploads\avatars
  files: /uploads/files/ #/uploads/files/ #C:\Users\BoBr\Documents\uploads\files
