jwt:
  secret: auhsdfuihpauisdfuhasiudhfuiasuiefjasndjgfbzkxclb/xm;dtjhyiodrtfhjknxdklfgjuiawergfuhasbfdfliughasyurgbhsjzrdgfhiuoshdufgisiarutghstyuerdghjksdfngjseruiygbsjdkfbgnjksdxbfjkgbserbghjdfj
  expiration: 3600000

spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: EECtbJuEldITiIfBBEIddigCmfvYutJf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
